# Generated by Django 3.2.5 on 2021-08-16 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Iso_code', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Code_name', models.CharField(max_length=100)),
                ('Start_date', models.DateField()),
                ('End_date', models.DateField()),
                ('Office_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wfp.country')),
            ],
        ),
    ]
