# Generated by Django 3.2.5 on 2021-08-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfp', '0002_auto_20210816_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='Iso_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='country',
            name='Name',
            field=models.CharField(max_length=100),
        ),
    ]
